apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deal
  template:
    metadata:
      labels:
        app: db-deal
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: deal
        - name: POSTGRES_PASSWORD
          value: "1"
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        name: db-deal
        ports:
        - containerPort: 5432
